language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
os:
- linux
script:
- mvn -U install
after_success:
- mvn site
- .travis/publish-javadoc.sh
env:
  matrix:
    secure: Ree/rivuW0MnCfeewYyRY6Jkth8c7D06qb8Lzz8D4OFUOVbw2IKd/OoaqjZ4d4ZiE0wJdakw9zHNvuHONCGIGDbpkKeBti/Cjt9mPZyPhG6i8k2cU1EksTlWE8RYDCn96Y3LqaIxl6VI8AfEzxnSPsvq4ljs/C5ntMv8NzNt9zG9pz6he8MQWgdY1mklimZG/oeuwpzgwqIWWvW0ib62jNWiVbDclKe7i4TK1r6Or0O3vSr6vQKjtq1Vhyv41dWxQ3bKzjuc5bBawq88abu5BHPAIveJhjVwxnFV+p16uujvaP598qk7XOw2vqubQ8c58YLajqAkrfr7u8lBiWx4sBlfDJpPijgLaSXhZqOyVSu98Snge4B/vkZQKZsdUtOLfPrFXL/onRIqTRlK+ayf4sGb/9fAj47V6Mzr/hWl27Pt9ZWhL6BizOijaTHWtQlPxe7vprsngU6uJ8m9Jvcfh81bxg2xPtQTh5w9yaXgYea+p5kqDkKJtz9yejxPUEKknmnLr8HV1eGshmY4skqdaRazs0bGd4+cmp/Pxy+AsiCb/2ahKRassrIUGTQ9l7NVlZzTmQ26+HT7fNmjy3uVyja3UxTjVCIpYK0pTJ+cTIWVTrJim+1e/+kz1ZKUB6R+JvQABj/wImPO4fIC6dsNtD/xeXKAsLnXf085CRPpV/k=
